openapi: 3.0.0
info:
  title: Exercise API
  version: 1.0.0
paths:
  /extract-text:
    post:
      tags:
      - "ocr"
      summary: Uploads a file and returns the text.
      operationId: uploadAndExtractText
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                example:
                  text: >
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                    eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                    enim ad minim veniam, quis nostrud exercitation ullamco laboris
                    nisi ut aliquip ex ea commodo consequat.
        '415':
          description: Unsupported Media Type
  /exercises:
    get:
      tags:
      - "exercises"
      summary: Get all exercises
      operationId: getExercises
      responses:
        '204':
          description: Status No Content
        '500':
          description: Internal Server Error
        '200':
          description: Successful response with exercise data
          content:
            application/json:
              example:
                exercises:
                  - id: 1
                    name: "Lorem Ipsum"
                  - id: 2
                    name: "Lorem Ipsum"
                  - id: 3
                    name: "Lorem Ipsum"
  '/exercises/{Id}':
    get:
      tags:
      - "exercises"
      summary: Get exercise
      operationId: getExercise
      parameters:
        - name: Id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Status No Content
        '500':
          description: Internal Server Error
        '200':
          description: Successful response with exercise data
          content:
            application/json:
              example:
                id: 1
                audio_path: "/path/audio.mp3"
                exercise_name: "lrem ispum"
    post:
      tags:
      - "exercises"
      summary: Submit Exercise
      operationId: submitExercise
      parameters:
        - name: Id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                exercise_id:
                  type: integer
                user_id:
                  type: integer
                gen_text:
                  type: string
      responses:
        '200':
          description: Score response
          content:
            application/json:
              example:
                score: 100